config/routes.rb
Rails.application.routes.draw do
  resources :movies
  root :to => redirect('/movies')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ActiveRecord::Base

    # scope :asc, -> (column) { order(column) }
    # scope :desc, -> (column) { reorder(column: :desc) }
    scope :sortmovies, -> (column, sortby) { order("#{column} #{sortby}") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    if params.has_key?(:column)
      if params.has_key?(:sortby)
        @movies= Movie.all.sortmovies(params[:column], params[:sortby].upcase)
      else
        @movies= Movie.all.sortmovies(params[:column], "asc")
      end
    else
      @movies = Movie.all
    end
    
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :rating, :description, :release_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rottenpotatoes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.text_field :rating %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :release_date, style: "display: block" %>
    <%= form.text_field :release_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movie.description %>
  </p>

  <p>
    <strong>Release date:</strong>
    <%= movie.release_date %>
  </p>

</div>

app/views/movies/edit.html.erb
<div style="padding-left: 500px">
  <div style="text-align: center; background: #ffb6c1; max-width: 50%">
    <h1>Editing movie</h1>

    <%= render "form", movie: @movie %>

    <br>

    <div>
      <%= link_to "Show this movie", @movie %> |
      <%= link_to "Back to movies", movies_path %>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<style>
  .sorted{
    background: yellow;
  }
  .hide{
    display: none;
  }
</style>
<p style="color: green"><%= notice %></p>
<div style="padding-left: 500px">
<div style="text-align: center; background: #fadadd; max-width: 50%">
<h1>Movies</h1>

<%= form_with url: movies_url, method: :get do |form| %>
  <%= radio_button_tag(:column, "title") %>
  <%= label_tag(:column, "title") %>
  <%= radio_button_tag(:column, "rating") %>
  <%= label_tag(:column, "rating") %>
  <%= radio_button_tag(:column, "release_date") %>
  <%= label_tag(:column, "release_date") %>

  <%= radio_button_tag(:sortby, "asc") %>
  <%= label_tag(:sortby, "asc") %>
  <%= radio_button_tag(:sortby, "desc") %>
  <%= label_tag(:sortby, "desc") %>
 
  <%= form.submit "Change order" %>
<% end %>

<div id="movies">
  <table> 
    <thead>
      <th> Title 
        <span class="<%= 'hide' unless params[:column]== 'title' && params[:sortby]!= 'desc' %>">&#8593;</span> 
        <span class="<%= 'hide' unless params[:column]== 'title' && params[:sortby]== 'desc' %>">&#8595;</span> 
      </th>
      <th> Rating 
        <span class="<%= 'hide' unless params[:column]== 'rating' && params[:sortby]!= 'desc' %>">&#8593;</span> 
        <span class="<%= 'hide' unless params[:column]== 'rating' && params[:sortby]== 'desc' %>">&#8595;</span> 
      </th>
      <th> Release 
        <span class="<%= 'hide' unless params[:column]== 'release_date' && params[:sortby]!= 'desc' %>">&#8593;</span> 
        <span class="<%= 'hide' unless params[:column]== 'release_date' && params[:sortby]== 'desc' %>">&#8595;</span> 
      </th>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td class="<%= 'sorted' if params[:column]== 'title' %>"><%= link_to movie.title, movie %></td>
          <td class="<%= 'sorted' if params[:column]== 'rating' %>"><%=movie.rating%></td>
          <td class="<%= 'sorted' if params[:column]== 'release_date' %>"><%=movie.release_date.to_date%></td>
        </tr>
      <% end %>
    </tbody>
    <tfooter>
    </tfooter>
  </table>
  
  <button>
    <%= link_to "New movie", new_movie_path %>
  </button>
</div>
</div>
</div>

app/views/movies/new.html.erb
<div style="padding-left: 500px">
  <div style="text-align: center; background: #ffb6c1; max-width: 50%">
  <h1>New movie</h1>

  <%= render "form", movie: @movie %>

  <br>

  <div>
    <%= link_to "Back to movies", movies_path %>
  </div>
</div>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>
<div style="padding-left: 500px">
  <div style="text-align: center; background: #ffb6c1; max-width: 50%">
    <h2><%= @movie.title %> </h2>
    <h3>Rotten Potatoes Rating: <%= @movie.rating %> </h3>
    <h3>Release Date: <%= @movie.release_date.to_date %> </h3>

    </div>

  <div style="background:  #ADD8E6; max-width: 50%">
    <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
    <%= link_to "Back to movies", movies_path %>

    <%= button_to "Destroy this movie", @movie, method: :delete %>
  </div>
</div>